### ISSUE TITLE
is neither a directory containing a "package.xml" file nor a file

### ISSUE THREAD

**Issue by Fellfalla** [athackst/vscode_ros2_workspace#23]
## How to Reproduce
0. Create your own workspace with custom packages and msgs, depending on each other.
1. Setup according to README.md
2. Run until step 

> Install dependencies Terminal->Run Task..->install dependencies

## Problem Description
When executing the Task `install dependencies` I receive following error within the DevContainer about a custom package:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/rosdep2/main.py", line 146, in rosdep_main
    exit_code = _rosdep_main(args)
  File "/usr/lib/python3/dist-packages/rosdep2/main.py", line 446, in _rosdep_main
    return _package_args_handler(command, parser, options, args)
  File "/usr/lib/python3/dist-packages/rosdep2/main.py", line 523, in _package_args_handler
    pkgs = find_catkin_packages_in(path, options.verbose)
  File "/usr/lib/python3/dist-packages/rosdep2/catkin_packages.py", line 35, in find_catkin_packages_in
    packages = find_packages(path)
  File "/usr/lib/python3/dist-packages/catkin_pkg/packages.py", line 92, in find_packages
    packages = find_packages_allowing_duplicates(basepath, exclude_paths=exclude_paths,
  File "/usr/lib/python3/dist-packages/catkin_pkg/packages.py", line 135, in find_packages_allowing_duplicates
    xmls[path] = _get_package_xml(os.path.join(basepath, path))
  File "/usr/lib/python3/dist-packages/catkin_pkg/package.py", line 516, in _get_package_xml
    raise IOError('Path "%s" is neither a directory containing a "%s" file nor a file' % (path, PACKAGE_MANIFEST_FILENAME))
OSError: Path "/workspaces/catkin_ws/install/share/custom_msgs" is neither a directory containing a "package.xml" file nor a file
```

## Modifiations
* In the Dockerfile: `FROM althack/ros2:foxy-dev` -> `FROM althack/ros2:galactic-dev`

**Comment by athackst** [comment]
If you're looking for the galactic version you should use that branch.

More than just the dockerfile should be changed to appropriately use this template with another version of ROS2  ( [see the diff](https://github.com/athackst/vscode_ros2_workspace/compare/galactic) )

**Comment by athackst** [comment]
Closing this for now.  Feel free to re-open if you have additional issues.
