### ISSUE TITLE
Error while reopening repo in a container on Mac

### ISSUE THREAD

**Issue by ivanrulik** [athackst/vscode_ros2_workspace#47]
Hi, 

my current setup:
- mac os (intel based)
- vs code installed
- docker installed
- vs code remote extensions installed

I hope that anyone can help me in this. I followed the steps to clone and re open this repo as a container and i got the following error in vs code:
```bash
[6294 ms] Start: Run: docker inspect --type container dc629ce7ee7b
[6414 ms] Error: Command failed: docker run --sig-proxy=false -a STDOUT -a STDERR --mount type=bind,source=/Users/ivanrulik/CODE/ros2_dev_container,target=/workspaces/ros2_dev_container,consistency=cached --mount type=volume,src=vscode,dst=/vscode -l devcontainer.local_folder=/Users/ivanrulik/CODE/ros2_dev_container -l devcontainer.config_file=/Users/ivanrulik/CODE/ros2_dev_container/.devcontainer/devcontainer.json -e DISPLAY=1 -e WAYLAND_DISPLAY= -e XDG_RUNTIME_DIR= -e PULSE_SERVER= -e LIBGL_ALWAYS_SOFTWARE=1 --network=host --cap-add=SYS_PTRACE --security-opt=seccomp:unconfined --security-opt=apparmor:unconfined --volume=/tmp/.X11-unix:/tmp/.X11-unix --volume=/mnt/wslg:/mnt/wslg --ipc=host --entrypoint /bin/sh vsc-ros2_dev_container-df507b15657988327cf272376c66a73783fb93c2df810e2fe3f884c937eeedc7 -c echo Container started
[6415 ms] trap "exit 0" 15
[6415 ms] exec "$@"
[6415 ms] while sleep 1 & wait $!; do :; done -
[6415 ms]     at Tse (/Users/ivanrulik/.vscode/extensions/ms-vscode-remote.remote-containers-0.292.0/dist/spec-node/devContainersSpecCLI.js:1946:3264)
[6415 ms]     at rO (/Users/ivanrulik/.vscode/extensions/ms-vscode-remote.remote-containers-0.292.0/dist/spec-node/devContainersSpecCLI.js:1946:3200)
[6415 ms]     at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
[6416 ms]     at async Xse (/Users/ivanrulik/.vscode/extensions/ms-vscode-remote.remote-containers-0.292.0/dist/spec-node/devContainersSpecCLI.js:1961:2626)
[6416 ms]     at async vh (/Users/ivanrulik/.vscode/extensions/ms-vscode-remote.remote-containers-0.292.0/dist/spec-node/devContainersSpecCLI.js:1961:3741)
[6416 ms]     at async gae (/Users/ivanrulik/.vscode/extensions/ms-vscode-remote.remote-containers-0.292.0/dist/spec-node/devContainersSpecCLI.js:2092:10213)
[6416 ms]     at async mae (/Users/ivanrulik/.vscode/extensions/ms-vscode-remote.remote-containers-0.292.0/dist/spec-node/devContainersSpecCLI.js:2092:9954)
[6422 ms] Exit code 1
```

<img width="873" alt="Screenshot 2023-05-13 at 10 34 56 AM" src="https://github.com/athackst/vscode_ros2_workspace/assets/49820318/ac9a2e4a-25ef-4cd1-a8a9-d58be0944fce">

In the docker extension of vs code I saw that the ros2_worksapce image was build and that a container is stopped. When I try to run the container I get this error message:

```bash
2023-05-13 10:31:41.694 [info] Error: Error response from daemon: Mounts denied: 
The path /mnt/wslg is not shared from the host and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> Resources -> File Sharing.
See https://docs.docker.com/desktop/mac for more info.
Error: failed to start containers: dc629ce7ee7b7b9bdc7a9ce2aa2dbdba4590472c79073fc0257f0a5e68b126e6
```

Any advice or help on this matter is greatly apreciated as I do like this repo to develop my ros projects

**Comment by ivanrulik** [comment]
It seems like the error got fixed when I commented out this line ("--volume=/mnt/wslg:/mnt/wslg",)  from thid file /.devcontainer/devcontainer.json
